<?php
// This class is needed to catch all the events that are generated by EventGenerator
//It would be used to display events on view events page
class EventHolder
{
    private $events = [];

    public function setEvents(Event $event){
        $this->events = $event; // using this instead of calling array_push, as it does not require any function calls and is faster;
    }

    /**
     * @return array
     */
    public function getEvents(): array
    {
        return $this->events;
    }
}